
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/mikolaj/apps/clion-2024.3.4/bin/cmake/linux/x64/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.11.0-25-generic - x86_64
...
